package com.skishop.entity;
// Generated 2019-11-19 23:45:26 by Hibernate Tools 5.2.3.Final

/**
 * Product1012 generated by hbm2java
 */
public class Product1012 implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String listimg;
	private Integer price;
	private Integer discountprice;

	public Product1012() {
	}

	public Product1012(String name, String description, String listimg, Integer price, Integer discountprice) {
		this.name = name;
		this.description = description;
		this.listimg = listimg;
		this.price = price;
		this.discountprice = discountprice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getListimg() {
		return this.listimg;
	}

	public void setListimg(String listimg) {
		this.listimg = listimg;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getDiscountprice() {
		return this.discountprice;
	}

	public void setDiscountprice(Integer discountprice) {
		this.discountprice = discountprice;
	}

}
