package com.skishop.entity;
// Generated 2019-11-21 22:57:03 by Hibernate Tools 5.2.3.Final



/**
 * User generated by hbm2java
 */
public class User {

	private int id;
	private String surname;
	private String name;
	private String email;
	private String password;

	public User() {
	}

	public User(int id, String surname, String email) {
		this.id = id;
		this.surname = surname;
		this.email = email;
	}
	public User(String surname,String name,String email,String password){
		this.surname=surname;
		this.name=name;
		this.email=email;
		this.password=password;
	}

	public User(int id, String surname, String name, String email, String password) {
		this.id = id;
		this.surname = surname;
		this.name = name;
		this.email = email;
		this.password = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
