package com.lwz.WS.entity;

import org.springframework.stereotype.Component;

/**
 * Person generated by hbm2java
 */
@Component
public class Person {
	private int id;
	private String username;
	private String password;
	private String email;
	private String address;

	public Person() {
	}

	public Person(int id) {
		this.id = id;
	}
	

	public Person(String username, String password, String email, String address) {
		super();
		this.username = username;
		this.password = password;
		this.email = email;
		this.address = address;
	}

	public Person(int id, String username, String password, String email, String address) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	public String toString() {
		return "Person [id=" + id + ", username=" + username + ", password=" + password + ", email=" + email
				+ ", address=" + address + "]";
	}
	

}
